package com.Potchen;

/**
 * Created by Joe on 2/22/2018.
 */
public enum TokenType {
    IF_TOK, ASSIGN_TOK, WHILE_TOK, PRINT_TOK, LESSEQ_TOK, LESS_TOK, GREATEREQ_TOK, GREATER_TOK, EQ_TOK, NOTEQ_TOK, ADD_TOK, SUB_TOK, MULT_TOK, DIV_TOK, ID_TOK, INT_TOK, REPEAT_TOK, UNTIL_TOK, DO_TOK, END_TOK,
    THEN_TOK, ELSE_TOK, EOS_TOK, PARENL_TOK, PARENR_Tok, EOL_TOK, FUNCTION_TOK
}
